# Generated by Django 4.0.5 on 2022-06-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el cliente', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=75, null=True)),
                ('ci', models.CharField(blank=True, help_text='Numero de carnet de Identidad', max_length=11, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Numero de telefono', max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=20, help_text='Latitud', max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=20, help_text='Longitud', max_digits=20)),
                ('direccion', models.CharField(help_text='Direccion completa', max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el mensajero', primary_key=True, serialize=False)),
                ('direcciones', models.ManyToManyField(blank=True, help_text='Direcciones del mensajero', to='core.direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el vehiculo del mensajero', primary_key=True, serialize=False)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoMensajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el vehiculo del mensajero', primary_key=True, serialize=False)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionServicioMensajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para la valoracion del servicio de mensajero', primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vahiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculomensajero')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioMensajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el vehiculo del mensajero', primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('destino', models.ForeignKey(blank=True, help_text='Direccion de destino', on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='core.direccion')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajero')),
                ('origen', models.ForeignKey(blank=True, help_text='Direccion de origen', on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='core.direccion')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vahiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculomensajero')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioServicioMensajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el comentario del servicio de mensajero', primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensajero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vahiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculomensajero')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direcciones',
            field=models.ManyToManyField(blank=True, help_text='Direcciones del cliente', to='core.direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
