# Generated by Django 4.0.5 on 2022-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_serviciomensajero_mensajero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciomensajero',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='serviciomensajero',
            name='origen',
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='latitud_destino',
            field=models.CharField(blank=True, help_text='Latitud Destino', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='latitud_origen',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitud Origen', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='longitud_destino',
            field=models.CharField(blank=True, help_text='Longitud Destino', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='longitud_origen',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Origen', max_digits=20, null=True),
        ),
    ]
