# Generated by Django 4.0.5 on 2022-06-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_serviciomensajero_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomensajero',
            name='latitud_origen',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitud Origen', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='serviciomensajero',
            name='longitud_origen',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Origen', max_digits=25, null=True),
        ),
    ]
