# Generated by Django 4.0.5 on 2022-06-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_serviciomensajero_latitud_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomensajero',
            name='latitud_destino',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitud Destino', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='serviciomensajero',
            name='longitud_destino',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Destino', max_digits=25, null=True),
        ),
    ]
