# Generated by Django 4.0.5 on 2022-06-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_serviciomensajero_latitud_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Destino', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='hora_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrega'),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='hora_recogida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de recogida'),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Destino', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='tarifa',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud Destino', max_digits=25, null=True),
        ),
    ]
