# Generated by Django 4.0.5 on 2022-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviciomensajero_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='direccion_destino',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='direccion_destino_map',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='direccion_origen',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='direccion_origen_map',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
