# Generated by Django 4.0.5 on 2022-06-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_serviciomensajero_direccion_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='estado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
