# Generated by Django 4.0.5 on 2022-06-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_serviciomensajero_activo_serviciomensajero_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
