# Generated by Django 4.0.5 on 2022-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mensajero_codigo_paquete_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='rechazo_mensajero',
            field=models.ManyToManyField(blank=True, related_name='rechazo_mensajero', to='core.mensajero'),
        ),
    ]
