# Generated by Django 4.0.5 on 2022-07-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_serviciomensajero_rechazo_mensajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='mensajero_rechazado',
            field=models.ManyToManyField(blank=True, related_name='mensajero_rechazado', to='core.mensajero'),
        ),
        migrations.AlterField(
            model_name='serviciomensajero',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE_DE_MENSAJERO', 'PENDIENTE_DE_MENSAJERO'), ('PENDIENTE_DE_ACEPTACION', 'PENDIENTE_DE_ACEPTACION'), ('ENVIANDO', 'ENVIANDO'), ('FINALIZADO', 'FINALIZADO')], max_length=25, null=True),
        ),
    ]
