# Generated by Django 4.0.5 on 2022-07-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_serviciomensajero_mensajero_rechazado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajero',
            name='paquete_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='paquete_entregado_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='paquete_recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='paquete_recogido_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='paquete_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='paquete_entregado_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='paquete_recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='paquete_recogido_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='paquete_recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviciomensajero',
            name='paquete_recogido_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
