# Generated by Django 4.0.5 on 2022-07-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mensajero_paquete_entregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomensajero',
            name='mensajero_aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
