# Generated by Django 4.0.5 on 2022-07-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_serviciomensajero_paquete_entregado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciomensajero',
            old_name='paquete_recogido',
            new_name='paquete_recibido',
        ),
        migrations.RenameField(
            model_name='serviciomensajero',
            old_name='paquete_recogido_hora',
            new_name='paquete_recibido_hora',
        ),
    ]
